SON-2227: es9618xx: fix error transceiver write_timeout
- Fixed: write_timeout value enlarged up to maximum
250ms. Lower timeout values caused to following
error: optoe XX-0050: Restore page register to 0 failed:-110!